# fly.toml app configuration file generated for throbbing-voice-7647 on 2023-09-06T15:11:55+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "throbbing-voice-7647"
primary_region = "lhr"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
